name: Website Test

on: deployment_status

permissions:
  pages: read

jobs:
  test:
    if: github.event.deployment_status == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: 'https://petegsx-projects.github.io/'
          exclude_url_prefix: 'mailto:'
          verbose: 'error'
          max_retry_time: 30
          max_retries: 5
          max_depth: 10